[package]
name = "fancy-test-macros"
version = "0.1.0"
authors = ["Russell Mull <russell@auxon.io>"]
edition = "2018"

[lib]
proc-macro = true
test = false

[dependencies]
proc-macro2 = "1.0.1"
quote = "1.0.2"
syn = { version = "1.0.5", features = ["full", "fold", "extra-traits"] }
